# Generated by Django 5.0.3 on 2024-07-19 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Football (Soccer)", "Football (Soccer)"),
                            ("Cycling", "Cycling"),
                            ("Swimming", "Swimming"),
                            ("Hiking", "Hiking"),
                            ("Tennis", "Tennis"),
                            ("Running", "Running"),
                            ("Gymnastics and Fitness", "Gymnastics and Fitness"),
                            (
                                "Winter Sports (Skiing, Snowboarding, Ice Skating)",
                                "Winter Sports (Skiing, Snowboarding, Ice Skating)",
                            ),
                            ("Handball", "Handball"),
                            ("Basketball", "Basketball"),
                            ("Yoga", "Yoga"),
                            ("Pilates", "Pilates"),
                            ("Zumba", "Zumba"),
                            ("Boxing", "Boxing"),
                            ("CrossFit", "CrossFit"),
                            ("Table Tennis", "Table Tennis"),
                            ("Horse Riding", "Horse Riding"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default="profile_images/default.png",
                        upload_to="profile_images/",
                    ),
                ),
                ("bio", models.TextField()),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="locations.city",
                    ),
                ),
                ("friends", models.ManyToManyField(blank=True, to="users.profile")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="custom_user_set", to="auth.group"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True, related_name="custom_user_set", to="auth.permission"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfileActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Advanced", "Advanced"),
                            ("Intermediate", "Intermediate"),
                            ("Beginner", "Beginner"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.activity"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.profile"
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "activity")},
            },
        ),
    ]
